### ISSUE TITLE
Info relating to ActivityPub

### ISSUE THREAD

**Issue by aschrijver** [vishalxl/decentralized-web-projects-list#2]
Nice list you started!

I am moderator at [SocialHub](https://socialhub.activitypub.rocks) and co-maintain several ActivityPub / Fediverse related lists:

- https://delightful.club/delightful-fediverse-apps/
- https://delightful.club/delightful-fediverse-clients/
- https://delightful.club/delightful-activitypub-development/

Though ActivityPub was standardized at W3C the SocialCG is at this moment not active, and SocialHub is the community forum attached to it, that is the location where fediverse technologists discuss matters that concern interoperability. Note also that Mastodon is by far the most popular fediverse app, but it also creates a confusion with people where they equate Mastodon with Fediverse, while the latter is much broader and holds great promis if it manages to evolve beyond microblogging spaces.

**Comment by vishalxl** [comment]
Hi, thanks for the info and feedback. I have added and edited some new info and link(s) about ActivityPub/Fediverse in the page.

**Comment by melvincarvalho** [comment]
Nice!  For reference this is a [thread](https://socialhub.activitypub.rocks/t/curated-list-of-non-proprietary-decentralized-projects/2491) I posted on the topic.
